/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assignmentSol from "./Assignment.sol";
export type { assignmentSol };
import type * as sushiTokenSol from "./sushiToken.sol";
export type { sushiTokenSol };
